version: 0.2

phases:
  install:
    runtime-versions:
      golang: "$GO_VERSION"
  build:
    commands:
      - cat /etc/os-release
      - echo Build started on `date`
      - go build -o main

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - main
    - templates/**/*
    - scripts/**/*
    - appspec.yml
    - .env
