version: 0.2

phases:
  build:
    commands:
      - cat /etc/os-release
      - echo Build started on `date`
      - GOOS=linux GOARCH=amd64 go build -o main

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - main
    - templates/**/*
    - scripts/**/*
    - appspec.yml
    - .env
